name: ooi-echo-matrix-decomp
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap
  - cartopy
  - dask
  - ipykernel
  - iris
  - jupyter
  - matplotlib
  - netCDF4
  - numpy
  - palettable
  - pandas
  - pip
  - python
  - requests
  - tensorly
  - scipy
  - scikit-learn
  - xarray
  - pip:
      - time-series-nmf
      - fbpca
      - git+https://github.com/ShunChi100/RobustPCA