name: ooi-echo-matrix-decomp
channels:
  - conda-forge
  - defaults
dependencies:
  - basemap
  - cartopy
  - dask
  - dill
  - ipykernel
  - iris
  - jupyter
  - matplotlib
  - netCDF4
  - numpy
  - palettable
  - pandas
  - pip
  - python
  - requests
  - scipy
  - scikit-learn==0.22.2.post1
  - seaborn
  - xarray
  - pip:
      - time-series-nmf
      - fbpca
      - git+https://github.com/ShunChi100/RobustPCA